### ISSUE TITLE
Ship generated data instead of using build.rs

### ISSUE THREAD

**Issue by Kijewski** [dahosek/finl_unicode#1]
A crate that accesses the internet during its build is extremely suspicious, even if it's only the Unicode data. Please just ship the derived data instead of building it on the fly.

docs.rs failed to build your crate, because it does not allow net access. For many users this will be the same, and they won't be able to use your project.

**Comment by Kijewski** [comment]
The documentation still doesn't build: https://docs.rs/crate/finl_unicode/1.0.1/builds/620110

Using a build script should be the last resort, if the information cannot be generated in advance.

**Comment by dahosek** [comment]
Yeah, I saw that. I’m working out how to restructure things so that I don’t use a build.rs, see https://www.reddit.com/r/rust/comments/x1nrtg/how_to_structure_replacement_for_buildrs_that/

**Comment by Kijewski** [comment]
Have a look if you can copy some ideas from <https://github.com/Kijewski/tzdb>. E.g. the Makefile, make-finl_unicode instead of make-tzdb, etc.
