### ISSUE TITLE
Implement `PeekChar` for `Iterator<Item=char>`

### ISSUE THREAD

**Issue by spencerwhite** [dahosek/finl_unicode#12]
I made a very small change that allows any `Iterator` over `char`s to use the `next_cluster()` function from `GraphemeCluster`. Admittedly, it got a little ugly in order to keep `CharIndices` implemented. I hope this would be a welcome addition since it makes the code much more generic, though admittedly more messy. Will submit a PR soon.

**Comment by dahosek** [comment]
Just to let you know that I have your PR on my to-do list for review.

**Comment by dahosek** [comment]
Do you have an example of `Iterator<Item=char>` that’s not `Chars`?

**Comment by dahosek** [comment]
Changes vetted and merged

**Comment by spencerwhite** [comment]
> Do you have an example of `Iterator<Item=char>` that’s not `Chars`?

Hey, I'm sorry I totally forgot to respond to this. School and all. Anyway, the idea was that I wanted to be able to find the nth grapheme cluster in a string without having to read the whole string. Then you could use it with async Streams and such
