### ISSUE TITLE
Fedora packaging problems

### ISSUE THREAD

**Issue by LecrisUT** [dahosek/finl_unicode#18]
Hi @dahosek @davide125,

We would like to package this rust package for Fedora in order to resolve other rust packages that indirectly depend on this. But we have some issues with licensing:
- #17 Unicode license due to generate code is not included in the `crate.toml`
  This one we can also solve on our side if any of you can confirm the licensing. @michel-slm and @decathrope know more on the details of what files are related to the license issue
- Usage of incompatible license in [resources/benchmark-texts](https://github.com/dahosek/finl_unicode/tree/master/resources/benchmark-texts)
  This is the main issue we are facing since we cannot download your source code because Fedora will inadvertently be "distributing" non-free source code. But since these files are used only for testing we were considering if:
  - #19 `resource/benchmark-texts` could be added to `package.exclude` in `cargo.toml`. This would be the easiest solution if you are ok with not having those files in the crate for the purpose of testing
  - decouple the testing so that it is done only in the workspace environment and it is not packages in the crate

Hope you can help us with this issue :pray:

**Comment by dahosek** [comment]
I will address this in the next release of finl_unicode which should be out in a few weeks at most.

**Comment by dahosek** [comment]
Fixed with new release
